<?php

namespace App\Enums;

enum ErrorCode: string
{
    case PASSKEY_NOT_SUPPORTED = 'PASSKEY_NOT_SUPPORTED';
    case PASSKEY_BACKEND_DISABLED = 'PASSKEY_BACKEND_DISABLED';
    case INVALID_REQUEST = 'INVALID_REQUEST';
    case CHALLENGE_EXPIRED = 'CHALLENGE_EXPIRED';
    case CHALLENGE_ALREADY_USED = 'CHALLENGE_ALREADY_USED';
    case CHALLENGE_NOT_FOUND = 'CHALLENGE_NOT_FOUND';
    case INVALID_ORIGIN = 'INVALID_ORIGIN';
    case INVALID_RP_ID = 'INVALID_RP_ID';
    case DUPLICATE_CREDENTIAL = 'DUPLICATE_CREDENTIAL';
    case CREDENTIAL_NOT_FOUND = 'CREDENTIAL_NOT_FOUND';
    case REGISTRATION_FAILED = 'REGISTRATION_FAILED';
    case AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED';
    case PASSKEY_VERIFICATION_FAILED = 'PASSKEY_VERIFICATION_FAILED';
    case UNAUTHORIZED = 'UNAUTHORIZED';
    case LAST_PASSKEY_DELETION_NOT_ALLOWED = 'LAST_PASSKEY_DELETION_NOT_ALLOWED';
    case SIGN_COUNT_MISMATCH = 'SIGN_COUNT_MISMATCH';
    case RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED';
}
